services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: spring
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    restart: unless-stopped

networks:
    postgres-network:
      driver: bridge

volumes:
  postgres-data: